export const WATCHER_TABLE = 4;
export const MINIONS_MAX_PER_PLAYER = 1;
export const DARK_AVENGERS_THREAT_INI_PER_PLAYER = 2;
export const DARK_AVENGERS_THREAT_MAX_PER_PLAYER = 12;
export const IRON_PATRIOT_LIFE_PER_PLAYER = 13;
export const IRON_PATRIOT_LIFE_EXP_PER_PLAYER = 15;
export const EXPOSED_THREAT_INI_PER_PLAYER = 4;
export const EXPOSED_THREAT_MAX_PER_PLAYER = 10;
