export const PhaseDict = {
  INIT: 0,
  TABLES: 1,
  SHIP_FALL: 2,
  ENEMY: 3,
  OSBORN_REVEAL: 4,
  VERANKE_LOSE: 5,
  VERANKE_WIN: 6,
  KINGDOM: 7,
  KINGDOM_DEFEATED: 8,
  EXPOSED: 9,
  CAPTAIN_LOSE: 10,
  CAPTAIN_WIN: 11
} as const;
export type Phase = (typeof PhaseDict)[keyof typeof PhaseDict];

export const HeroesDict = {
  ADAM_WARLOCK: "Adam Warlock",
  ANGEL: "Ángel",
  ANT_MAN: "Hombre Hormiga",
  BISHOP: "Bishop",
  BLACK_PANTHER_SHURI: "Pantera Negra (Shuri)",
  BLACK_PANTHER_TCHALLA: "Pantera Negra (Tchalla)",
  BLACK_WIDOW: "Viuda Negra",
  CABLE: "Cable",
  CAPTAIN_AMERICA: "Capitán América",
  CAPTAIN_MARVEL: "Capitana Marvel",
  COLOSSUS: "Coloso",
  CYCLOPS: "Cíclope",
  DAREDEVIL: "Daredevil",
  DEADPOOL: "Masacre",
  DOCTOR_STRANGE: "Doctor Extraño",
  DOMINO: "Dominó",
  DRAX: "Drax",
  ELEKTRA: "Elektra",
  FALCON: "Halcón",
  GAMBIT: "Gambito",
  GAMORA: "Gamora",
  GHOST_SPIDER: "Ghost Spider",
  GROOT: "Groot",
  HAWKEYE: "Ojo de Halcón",
  HERCULES: "Hércules",
  HULK: "Hulk",
  HULKLING: "Hulkling",
  HUMAN_TORCH: "Antorcha Humana",
  ICE_MAN: "Hombre de Hielo",
  INVISIBLE_WOMAN: "Mujer Invisible",
  IRON_FIST: "Puño de Hierro",
  IRON_MAN: "Iron Man",
  IRON_HEART: "Ironheart",
  JESSICA_JONES: "Jessica Jones",
  JUBILEE: "Júbilo",
  LUKE_CAGE: "Luke Cage",
  MAGIK: "Magik",
  MAGNETO: "Magneto",
  MARIA_HILL: "María Hill",
  MR_FANTASTIC: "Mr. Fantástico",
  MS_MARVEL: "Ms. Marvel",
  NEBULA: "Nébula",
  NICK_FURY: "Nick Furia",
  NIGHTCRAWLER: "Rondador Nocturno",
  NOVA: "Nova",
  PHOENIX: "Fénix",
  PSYLOCKE: "Mariposa Mental",
  PUNISHER: "El Castigador",
  QUICKSILVER: "Mercurio",
  ROCKET_RACOON: "Mapache Cohete",
  ROGUE: "Pícara",
  SCARLET_WITCH: "Bruja Escarlata",
  SHADOWCAT: "Gatasombra",
  SHE_HULK: "Hulka",
  SILK: "Seda",
  SP_DR: "SP//dr",
  SPECTRUM: "Spectrum",
  SPIDER_HAM: "Spider-Ham",
  SPIDER_MAN_PETER: "Spiderman (Peter Parker)",
  SPIDER_MAN_MILES: "Spider-Man (Miles Morales)",
  SPIDER_WOMAN: "Spider Woman",
  STAR_LORD: "Star Lord",
  STORM: "Tormenta",
  THING: "La Cosa",
  THOR: "Thor",
  TIGRA: "Tigra",
  VALKYRIE: "Valquiria",
  VENOM: "Veneno",
  VISION: "Visión",
  WAR_MACHINE: "Máquina de Guerra",
  WASP: "Avispa",
  WINTER_SOLDIER: "Soldado de Invierno",
  WOLVERINE: "Lobezno",
  WONDER_MAN: "Wonder Man",
  X_23: "X-23"
} as const satisfies Record<string, string>;
export type Hero = (typeof HeroesDict)[keyof typeof HeroesDict];
export const BannedHeroes: Hero[] = [];
